name = "caffeine_cli"
version = "4.0.2"
description = "CLI for the Caffeine compiler."
licences = ["GPL-3.0"]

target = "erlang"

[dependencies]
caffeine_lang = { path = "../caffeine_lang" }
gleam_stdlib = ">= 0.63.0 and < 1.0.2"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glint = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.2"
