name = "caffeine_lang"
version = "0.1.0"
description = "A compiler for generating reliability artifacts from service expectation definitions."
licences = ["GPL-3.0"]

repository = { type = "github", user = "Brickell-Research", repo = "caffeine_lang" }
links = [
    { title = "Website", href = "https://github.com/Brickell-Research/caffeine_lang" },
]

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.63.0 and < 1.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
glaml = "~> 3.0.0"
gleeunit = ">= 1.0.0"
caffeine_query_language = ">= 0.0.2"
