name: Gleamy Spec Package Test

on:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/gleamy_spec/**'
      - '.github/workflows/test_gleamy_spec.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'lib/gleamy_spec/**'
      - '.github/workflows/test_gleamy_spec.yml'

jobs:
  test:
    name: Test Gleamy Spec on Gleam ${{ matrix.gleam-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # latest three versions of gleam
        gleam-version: ["1.11.0", "1.12.0", "1.13.0"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup BEAM (Erlang + Gleam + rebar3)
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        gleam-version: ${{ matrix.gleam-version }}
        rebar3-version: '3.25.0'
        
    - name: Cache Gleam dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/gleam
          lib/cql/build
        key: ${{ runner.os }}-gleam-gleamy_spec-${{ matrix.gleam-version }}-${{ hashFiles('lib/gleamy_spec/manifest.toml') }}
        restore-keys: |
          ${{ runner.os }}-gleam-gleamy_spec-${{ matrix.gleam-version }}-
          ${{ runner.os }}-gleam-gleamy_spec-
          
    - name: Download dependencies
      run: gleam deps download
      working-directory: lib/gleamy_spec
      
    - name: Compile
      run: gleam build
      working-directory: lib/gleamy_spec
      
    - name: Run tests
      run: gleam test
      working-directory: lib/gleamy_spec
